In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib
from matplotlib import pyplot as plt
# # SciKitLearn is a useful machine learning utilities library
# import sklearn
# # The sklearn dataset module helps generating |datasets
# import sklearn.datasets
# import sklearn.linear_model
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.preprocessing import normalize
# from scipy.stats import gaussian_kde
import pandas as pd


In [2]:
# Import Dataset
qcd_raw = pd.read_csv('../EventPlotting/qcd_outputDataForLearning.csv')
hh_raw = pd.read_csv('../EventPlotting/dihiggs_outputDataForLearning.csv')

In [3]:
qcd_raw.head()
print(len(qcd_raw), "rows of qcd data")
hh_raw.head()
print(len(hh_raw), "rows of dihiggs data")

1703 rows of qcd data
4605 rows of dihiggs data


In [10]:
# Make higgs and qcd sets from raw data
hh_all = hh_raw[['h1_mass', 'h2_mass', 'deltaR(h1 jets)', 'deltaR(h2 jets)']]
qcd = qcd_raw[['h1_mass', 'h2_mass', 'deltaR(h1 jets)', 'deltaR(h2 jets)']]

In [11]:
hh_all = np.array(hh_all)
qcd = np.array(qcd)

In [12]:
# add labels to di-higgs
hh_all=hh_all[:,:4]
# print(hh[0:3])
hh_labels= np.zeros((len(hh_all),1))
hh_labels = hh_labels+1
#a = hh[:len(hh)]
# print(a.shape)
hh_all = np.append(hh_all, hh_labels, axis=1)
# print(hh.shape)
# print(hh[0:3])

In [18]:
# add labels to qcd
qcd=qcd[:,:4]
# print(hh[0:3])
qcd_labels= np.zeros((len(qcd),1))
qcd_labels = qcd_labels+1
#a = hh[:len(hh)]
# print(a.shape)
qcd = np.append(qcd, qcd_labels, axis=1)
# print(hh.shape)
# print(hh[0:3])
print(qcd[:4])

[[124.32560775 111.57092015   2.30806958   1.8907895    1.        ]
 [ 44.27017863  50.02795445   0.53594587   0.67197657   1.        ]
 [ 26.86431539  97.05075322   0.50002477   1.24722521   1.        ]
 [ 52.99052297  68.4701516    0.85636988   1.41845491   1.        ]]


In [16]:
# select a quarter of hh events so that the set is half and half
hh = hh[0:len(qcd)]

In [29]:
test_data = np.append(hh[:4],qcd[:4]) 
print(test_data)

[148.29183647 158.29664593   2.39941158   3.04517197   1.
  96.55363983  58.55460135   1.3437355    1.1183898    1.
 110.27188042 130.16422715   0.69737734   1.15238492   1.
 179.64052569 166.13619263   2.05337635   2.09055659   1.
 124.32560775 111.57092015   2.30806958   1.8907895    1.
  44.27017863  50.02795445   0.53594587   0.67197657   1.
  26.86431539  97.05075322   0.50002477   1.24722521   1.
  52.99052297  68.4701516    0.85636988   1.41845491   1.        ]


In [32]:
np.random.shuffle(test_data)
print(test_data)

[ 96.55363983   1.           1.1183898  179.64052569   0.53594587
 124.32560775 110.27188042   1.24722521  58.55460135 130.16422715
   1.           1.          97.05075322  50.02795445  44.27017863
   0.67197657   0.85636988  26.86431539   1.8907895    2.05337635
   1.15238492   1.           3.04517197 166.13619263 158.29664593
   1.          52.99052297   2.09055659  68.4701516    1.
   2.39941158   2.30806958   1.           1.41845491   0.69737734
   0.50002477   1.         111.57092015   1.3437355  148.29183647]


In [22]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([6, 0, 4, 1, 3, 9, 7, 8, 5, 2])

In [27]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
