In [1]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense1 = nn.Linear(2,5)
        self.dense2 = nn.Linear(5,5)
        self.dense3 = nn.Linear(5,1)
        
    def forward(self, x):
        x = self.dense1(x)
        x = F.relu(x)
        x = self.dense2(x)
        x = F.relu(x)
        x = self.dense3(x)
        x = self.sigmoid(x)
        return x

In [3]:
criterion = nn.MSELoss()
net = Net()
print(list(net.parameters()))
optimizer = optim.SGD(net.parameters(),lr=0.01)


[Parameter containing:
tensor([[-0.1075,  0.5397],
        [ 0.1570, -0.1336],
        [-0.1701,  0.0830],
        [-0.2409,  0.4176],
        [-0.2192, -0.2259]], requires_grad=True), Parameter containing:
tensor([-0.6124, -0.4154,  0.2429, -0.1535, -0.3596], requires_grad=True), Parameter containing:
tensor([[-0.0059, -0.1177, -0.0071,  0.4431,  0.0933],
        [ 0.3762,  0.1138,  0.4004, -0.1875,  0.4000],
        [ 0.4139,  0.3590,  0.1364,  0.1032,  0.1852],
        [-0.2194,  0.0670,  0.1126, -0.0588, -0.3163],
        [ 0.4470,  0.2787, -0.2202,  0.2967, -0.3046]], requires_grad=True), Parameter containing:
tensor([-0.0774, -0.3737, -0.1824, -0.1888, -0.1281], requires_grad=True), Parameter containing:
tensor([[-0.1504,  0.1083, -0.0303,  0.0913,  0.0826]], requires_grad=True), Parameter containing:
tensor([-0.0389], requires_grad=True)]


In [4]:
x = net.parameters().__next__()

In [5]:
print("{}".format(x.data))
print("{}".format(x.grad))

tensor([[-0.1075,  0.5397],
        [ 0.1570, -0.1336],
        [-0.1701,  0.0830],
        [-0.2409,  0.4176],
        [-0.2192, -0.2259]])
None


In [6]:
input = Tensor(torch.rand(1,2), requires_grad=True)

NameError: name 'Tensor' is not defined